version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wp_local
    restart: always
    ports:
      - "8080:80"  # Visit http://localhost:8080 to see your WordPress site
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./:/var/www/html/wp-content/themes/edenjoyauthor.com
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # Visit http://localhost:8081 for phpMyAdmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  wordpress_data:
  db_data: