name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: lukas2511/ftp-deploy-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: .  # Deploy the entire repository
          remote-dir: "/home2/thbbqvmy/edenjoyauthor.com/public_html/wp-content/themes/edenjoyauthor.com"  # Change this to your FTP server path
          cleanup: true  # Optional: Remove remote files not in repo