name: Deploy to FTP

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22  # Change this if your project requires a different Node.js version
          cache: 'npm'  # Cache node_modules for faster builds

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./"  # Deploy the entire repository
          server-dir: "./edenjoyauthor.com/"  # Change this to your FTP server path